replicaCount: 1

image:
  repository: postgres
  tag: "13"

postgres:
  db: changeme
  user: changeme
  password: changeme

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  type: ClusterIP
  port: 5432
